/* Generated By:JJTree: Do not edit this line. ExpoExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class ExpoExp extends SimpleNode {
  public ExpoExp(int id) {
    super(id);
  }

  public ExpoExp(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=349528f24b4a68c113b74f9482779eeb (do not edit this line) */
