/* Generated By:JJTree: Do not edit this line. FromClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class FromClause extends SimpleNode {
  public FromClause(int id) {
    super(id);
  }

  public FromClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a2f24a83e9e5ae99f83fff238f36cc1a (do not edit this line) */
