/* Generated By:JJTree: Do not edit this line. From.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class From extends SimpleNode {
  public From(int id) {
    super(id);
  }

  public From(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=405fca1ff1fe9c070bc95191b9cd0f4f (do not edit this line) */
