/* Generated By:JJTree: Do not edit this line. GroupByClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class GroupByClause extends SimpleNode {
  public GroupByClause(int id) {
    super(id);
  }

  public GroupByClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=205d1285d1198d78f4abcfa62dec16ee (do not edit this line) */
