/* Generated By:JJTree: Do not edit this line. MultiplyExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class MultiplyExp extends SimpleNode {
  public MultiplyExp(int id) {
    super(id);
  }

  public MultiplyExp(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f25f5162157f13a7e11acbaef67866e4 (do not edit this line) */
