/* Generated By:JJTree: Do not edit this line. MultiplyOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class MultiplyOp extends SimpleNode {
  public MultiplyOp(int id) {
    super(id);
  }

  public MultiplyOp(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3593e879f7a1b92b19e3d20011a51f08 (do not edit this line) */
