/* Generated By:JJTree: Do not edit this line. ObjectReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class ObjectReference extends SimpleNode {
  public ObjectReference(int id) {
    super(id);
  }

  public ObjectReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5d81d64aeeac49b6fa7948564c52c99 (do not edit this line) */
