/* Generated By:JJTree: Do not edit this line. OrderByClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class OrderByClause extends SimpleNode {
  public OrderByClause(int id) {
    super(id);
  }

  public OrderByClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cc8f2c83ef8b72ad334563657e41fc8d (do not edit this line) */
