/* Generated By:JavaCC: Do not edit this line. PlSqlTreeConstants.java Version 5.0 */
package qopt;

@SuppressWarnings("all")
public interface PlSqlTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTSEL = 2;
  public int JJTPROJ = 3;
  public int JJTFROM = 4;
  public int JJTWHERE = 5;
  public int JJTSIMPLEEXP = 6;
  public int JJTSIMPLEOP = 7;
  public int JJTMULTIPLYEXP = 8;
  public int JJTMULTIPLYOP = 9;
  public int JJTEXPOEXP = 10;
  public int JJTUNARYEXP = 11;
  public int JJTPRIMEXP = 12;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Sel",
    "Proj",
    "From",
    "where",
    "SimpleExp",
    "SimpleOp",
    "MultiplyExp",
    "MultiplyOp",
    "ExpoExp",
    "UnaryExp",
    "PrimExp",
  };
}
/* JavaCC - OriginalChecksum=64c34015e719375f818fca39a8bf828c (do not edit this line) */
