/* Generated By:JJTree: Do not edit this line. PrimExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class PrimExp extends SimpleNode {
  public PrimExp(int id) {
    super(id);
  }

  public PrimExp(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d4fa6e23290045a1b6272e1aa1647c5 (do not edit this line) */
