/* Generated By:JJTree: Do not edit this line. Proj.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class Proj extends SimpleNode {
  public Proj(int id) {
    super(id);
  }

  public Proj(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73e9613b8dfcfd0f2ea30f0ef9f9fcd8 (do not edit this line) */
