/* Generated By:JJTree: Do not edit this line. QueryTableExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class QueryTableExpression extends SimpleNode {
  public QueryTableExpression(int id) {
    super(id);
  }

  public QueryTableExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dfcc0e5a121692e846b65764f8d0c2df (do not edit this line) */
