/* Generated By:JJTree: Do not edit this line. Relop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class Relop extends SimpleNode {
  public Relop(int id) {
    super(id);
  }

  public Relop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a00c92960234e1cfa7018a543bd9284e (do not edit this line) */
