/* Generated By:JJTree: Do not edit this line. Root.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class Root extends SimpleNode {
  public Root(int id) {
    super(id);
  }

  public Root(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=71c034b50a6c75d8a3de7553ab97a036 (do not edit this line) */
