/* Generated By:JJTree: Do not edit this line. Sel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class Sel extends SimpleNode {
  public Sel(int id) {
    super(id);
  }

  public Sel(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4eb36d6dd08d11bf3d4eb8d77f5bd7d1 (do not edit this line) */
