/* Generated By:JJTree: Do not edit this line. SelectSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SelectSet extends SimpleNode {
  public SelectSet(int id) {
    super(id);
  }

  public SelectSet(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ec3899c70acf2c0ab3bec1c68b7c4f86 (do not edit this line) */
