/* Generated By:JJTree: Do not edit this line. SelectItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SelectItem extends SimpleNode {
  public SelectItem(int id) {
    super(id);
  }

  public SelectItem(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f4b8ff798652a19d5910c45c578333c9 (do not edit this line) */
