/* Generated By:JJTree: Do not edit this line. SimpleExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SimpleExp extends SimpleNode {
  public SimpleExp(int id) {
    super(id);
  }

  public SimpleExp(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e9f809d6bfaf3bc8881dd4c9c181cbee (do not edit this line) */
