/* Generated By:JJTree: Do not edit this line. SimpleOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SimpleOp extends SimpleNode {
  public SimpleOp(int id) {
    super(id);
  }

  public SimpleOp(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7674890c353419f0e1c49bef010d765d (do not edit this line) */
