/* Generated By:JJTree: Do not edit this line. SQLAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLAndExpression extends SimpleNode {
  public SQLAndExpression(int id) {
    super(id);
  }

  public SQLAndExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba7b2c7f3d17188938f08fc618b96c17 (do not edit this line) */
