/* Generated By:JJTree: Do not edit this line. SQLExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLExpressionList extends SimpleNode {
  public SQLExpressionList(int id) {
    super(id);
  }

  public SQLExpressionList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e745995aef2bfe3f74b280c5cce13c4b (do not edit this line) */
