/* Generated By:JJTree: Do not edit this line. SQLInClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLInClause extends SimpleNode {
  public SQLInClause(int id) {
    super(id);
  }

  public SQLInClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c21900b6641b622c8ee388e62d0d0673 (do not edit this line) */
