/* Generated By:JJTree: Do not edit this line. SQLLikeClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLLikeClause extends SimpleNode {
  public SQLLikeClause(int id) {
    super(id);
  }

  public SQLLikeClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7680efbfe4a2829ce812b42138df272 (do not edit this line) */
