/* Generated By:JJTree: Do not edit this line. SQLRelationalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLRelationalExpression extends SimpleNode {
  public SQLRelationalExpression(int id) {
    super(id);
  }

  public SQLRelationalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af3fa0a947b83fd778ba23d419f91175 (do not edit this line) */
