/* Generated By:JJTree: Do not edit this line. SQLRelationalOperatorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLRelationalOperatorExpression extends SimpleNode {
  public SQLRelationalOperatorExpression(int id) {
    super(id);
  }

  public SQLRelationalOperatorExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=774f5506af2c5747a1953a84e694314a (do not edit this line) */
