/* Generated By:JJTree: Do not edit this line. SQLUnaryLogicalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class SQLUnaryLogicalExpression extends SimpleNode {
  public SQLUnaryLogicalExpression(int id) {
    super(id);
  }

  public SQLUnaryLogicalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=58b7257b5b753f786efd0aa171abf688 (do not edit this line) */
