/* Generated By:JJTree: Do not edit this line. TableName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class TableName extends SimpleNode {
  public TableName(int id) {
    super(id);
  }

  public TableName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f2a4e992762ba3fd86952f67cea714d7 (do not edit this line) */
