/* Generated By:JJTree: Do not edit this line. TableColumn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class TableColumn extends SimpleNode {
  public TableColumn(int id) {
    super(id);
  }

  public TableColumn(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae26b8087e1a4dc7733d0e8d37c5a57c (do not edit this line) */
