/* Generated By:JJTree: Do not edit this line. WhereClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class WhereClause extends SimpleNode {
  public WhereClause(int id) {
    super(id);
  }

  public WhereClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2974f212f6a94de4b99e98526f5db526 (do not edit this line) */
