/* Generated By:JJTree: Do not edit this line. where.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package qopt;

public
@SuppressWarnings("all")
class where extends SimpleNode {
  public where(int id) {
    super(id);
  }

  public where(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5e50f2fc5a11c9b9e6b003efbd55b029 (do not edit this line) */
