/* Generated By:JJTree: Do not edit this line. Arguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Arguments extends SimpleNode {
  public Arguments(int id) {
    super(id);
  }

  public Arguments(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=842feda935d8e50183a37b82ad0fb0a3 (do not edit this line) */
