/* Generated By:JJTree: Do not edit this line. BasicDataTypeDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class BasicDataTypeDefinition extends SimpleNode {
  public BasicDataTypeDefinition(int id) {
    super(id);
  }

  public BasicDataTypeDefinition(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ac6e0615bd396cff97f7f0a71e91948 (do not edit this line) */
