/* Generated By:JJTree: Do not edit this line. BindVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class BindVariable extends SimpleNode {
  public BindVariable(int id) {
    super(id);
  }

  public BindVariable(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=949e7053b1e868d30a7dff54471d96de (do not edit this line) */
