/* Generated By:JJTree: Do not edit this line. CloseStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class CloseStatement extends SimpleNode {
  public CloseStatement(int id) {
    super(id);
  }

  public CloseStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29495b69706dc7969f4394187497d821 (do not edit this line) */
