/* Generated By:JJTree: Do not edit this line. ColumnValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ColumnValue extends SimpleNode {
  public ColumnValue(int id) {
    super(id);
  }

  public ColumnValue(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df71aed9d5058c56527df66c151c04bb (do not edit this line) */
