/* Generated By:JJTree: Do not edit this line. ColumnValues.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ColumnValues extends SimpleNode {
  public ColumnValues(int id) {
    super(id);
  }

  public ColumnValues(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b48f6ef0556b33dda921a35c7f0b6ea (do not edit this line) */
