/* Generated By:JJTree: Do not edit this line. ColumnName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ColumnName extends SimpleNode {
  public ColumnName(int id) {
    super(id);
  }

  public ColumnName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5870a0b4bc09f7bd1bea69adff4f59d3 (do not edit this line) */
