/* Generated By:JJTree: Do not edit this line. ColumnDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ColumnDefinition extends SimpleNode {
  public ColumnDefinition(int id) {
    super(id);
  }

  public ColumnDefinition(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6269452809cb2e6c8e2dd388b53a3b2 (do not edit this line) */
