/* Generated By:JJTree: Do not edit this line. ConstantDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ConstantDeclaration extends SimpleNode {
  public ConstantDeclaration(int id) {
    super(id);
  }

  public ConstantDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=acc41fed44bea1afa23bbf3bd4db37a7 (do not edit this line) */
