/* Generated By:JJTree: Do not edit this line. CursorReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class CursorReference extends SimpleNode {
  public CursorReference(int id) {
    super(id);
  }

  public CursorReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a4a53e0064fd29dbbe433bec1714888a (do not edit this line) */
