/* Generated By:JJTree: Do not edit this line. CursorForLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class CursorForLoop extends SimpleNode {
  public CursorForLoop(int id) {
    super(id);
  }

  public CursorForLoop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d46e019447620e60d0ba1700a5b670dc (do not edit this line) */
