/* Generated By:JJTree: Do not edit this line. CursorDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class CursorDeclaration extends SimpleNode {
  public CursorDeclaration(int id) {
    super(id);
  }

  public CursorDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e9eca472bba565ab8c8aa4ce74bff453 (do not edit this line) */
