/* Generated By:JJTree: Do not edit this line. DataItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class DataItem extends SimpleNode {
  public DataItem(int id) {
    super(id);
  }

  public DataItem(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6cc1ae98e2d373b93ed40599c1daa943 (do not edit this line) */
