/* Generated By:JJTree: Do not edit this line. DatetimeField.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class DatetimeField extends SimpleNode {
  public DatetimeField(int id) {
    super(id);
  }

  public DatetimeField(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=54bda82c82cbd48637f11ccae27efccf (do not edit this line) */
