/* Generated By:JJTree: Do not edit this line. DeclarationSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class DeclarationSection extends SimpleNode {
  public DeclarationSection(int id) {
    super(id);
  }

  public DeclarationSection(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=690e9bb4c573bda072ede30b54c4022b (do not edit this line) */
