/* Generated By:JJTree: Do not edit this line. Declarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Declarations extends SimpleNode {
  public Declarations(int id) {
    super(id);
  }

  public Declarations(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=af1092ec9d630827e1c577ffc377cae5 (do not edit this line) */
