/* Generated By:JJTree: Do not edit this line. DeleteStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class DeleteStatement extends SimpleNode {
  public DeleteStatement(int id) {
    super(id);
  }

  public DeleteStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e6160597d6fe1b9f48d254ef8b264325 (do not edit this line) */
