/* Generated By:JJTree: Do not edit this line. ForallStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ForallStatement extends SimpleNode {
  public ForallStatement(int id) {
    super(id);
  }

  public ForallStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=439b505c6e4a6b9728fbc5225e49e041 (do not edit this line) */
