/* Generated By:JJTree: Do not edit this line. ForUpdateClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ForUpdateClause extends SimpleNode {
  public ForUpdateClause(int id) {
    super(id);
  }

  public ForUpdateClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0d85b3222d0813ae2adbeeab88bee09 (do not edit this line) */
