/* Generated By:JJTree: Do not edit this line. FunctionDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class FunctionDeclaration extends SimpleNode {
  public FunctionDeclaration(int id) {
    super(id);
  }

  public FunctionDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7c2c8e768e18f427385125c0c3419307 (do not edit this line) */
