/* Generated By:JJTree: Do not edit this line. FunctionReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class FunctionReference extends SimpleNode {
  public FunctionReference(int id) {
    super(id);
  }

  public FunctionReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ea3331c6e4a213b45e1655c8bc06dfb7 (do not edit this line) */
