/* Generated By:JJTree: Do not edit this line. FunctionArgumentList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class FunctionArgumentList extends SimpleNode {
  public FunctionArgumentList(int id) {
    super(id);
  }

  public FunctionArgumentList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d95f2c74556ec8a91c7249e37f32a8d8 (do not edit this line) */
