/* Generated By:JJTree: Do not edit this line. FunctionCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class FunctionCall extends SimpleNode {
  public FunctionCall(int id) {
    super(id);
  }

  public FunctionCall(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d3241023cfa0e15c7e13a64c7ad55cfd (do not edit this line) */
