/* Generated By:JJTree: Do not edit this line. FunctionArgument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class FunctionArgument extends SimpleNode {
  public FunctionArgument(int id) {
    super(id);
  }

  public FunctionArgument(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b3754a857425b8ba1eea9d7fbb1cca6 (do not edit this line) */
