/* Generated By:JJTree: Do not edit this line. GotoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class GotoStatement extends SimpleNode {
  public GotoStatement(int id) {
    super(id);
  }

  public GotoStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=961e2c961af07a9ecf08327c034294e6 (do not edit this line) */
