/* Generated By:JJTree: Do not edit this line. GroupByClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class GroupByClause extends SimpleNode {
  public GroupByClause(int id) {
    super(id);
  }

  public GroupByClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df52e5ca8bb6de2d760331a85896f8d0 (do not edit this line) */
