/* Generated By:JJTree: Do not edit this line. HavingClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class HavingClause extends SimpleNode {
  public HavingClause(int id) {
    super(id);
  }

  public HavingClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b6d4ec89f65413906d918c362f85871 (do not edit this line) */
