/* Generated By:JJTree: Do not edit this line. ID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ID extends SimpleNode {
  public ID(int id) {
    super(id);
  }

  public ID(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=997d58a0e7ef23a72ebab397f91380b0 (do not edit this line) */
