/* Generated By:JJTree: Do not edit this line. IdentifierDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class IdentifierDeclaration extends SimpleNode {
  public IdentifierDeclaration(int id) {
    super(id);
  }

  public IdentifierDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=703c2a6614924d293e3a47e69376baba (do not edit this line) */
