/* Generated By:JJTree: Do not edit this line. InlineTVBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class InlineTVBody extends SimpleNode {
  public InlineTVBody(int id) {
    super(id);
  }

  public InlineTVBody(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1e34954ff9e810fbe1a63ce3a15f079 (do not edit this line) */
