/* Generated By:JJTree: Do not edit this line. InsertStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class InsertStatement extends SimpleNode {
  public InsertStatement(int id) {
    super(id);
  }

  public InsertStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aae414efd9eb9b96ca0ece0753a939d1 (do not edit this line) */
