/* Generated By:JJTree: Do not edit this line. IntervalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class IntervalExpression extends SimpleNode {
  public IntervalExpression(int id) {
    super(id);
  }

  public IntervalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70d0b0e205c552968f40c24ae5f95a5a (do not edit this line) */
