/* Generated By:JJTree: Do not edit this line. IntoClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class IntoClause extends SimpleNode {
  public IntoClause(int id) {
    super(id);
  }

  public IntoClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=875ee5a9465b0f5e9f04cae924ae647e (do not edit this line) */
