/* Generated By:JJTree: Do not edit this line. Join.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Join extends SimpleNode {
  public Join(int id) {
    super(id);
  }

  public Join(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce90709fbf3a7724bd82f8ea3f80feb8 (do not edit this line) */
