/* Generated By:JJTree: Do not edit this line. LabelDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class LabelDeclaration extends SimpleNode {
  public LabelDeclaration(int id) {
    super(id);
  }

  public LabelDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f18d4b7a9a6d96b5f5264e90f2e4cdcb (do not edit this line) */
