/* Generated By:JJTree: Do not edit this line. LoopStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class LoopStatement extends SimpleNode {
  public LoopStatement(int id) {
    super(id);
  }

  public LoopStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a11d38acda0bbf0bed3f567ac642896 (do not edit this line) */
