/* Generated By:JJTree: Do not edit this line. MergeStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class MergeStatement extends SimpleNode {
  public MergeStatement(int id) {
    super(id);
  }

  public MergeStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=074da8ec9f9ca7542577851139ab7cc2 (do not edit this line) */
