/* Generated By:JJTree: Do not edit this line. NullStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class NullStatement extends SimpleNode {
  public NullStatement(int id) {
    super(id);
  }

  public NullStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=411f8cd419d8a84ae7e5a106e01ee200 (do not edit this line) */
