/* Generated By:JJTree: Do not edit this line. NumericForLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class NumericForLoop extends SimpleNode {
  public NumericForLoop(int id) {
    super(id);
  }

  public NumericForLoop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88090b3675fb238d35ca2d494aa86d53 (do not edit this line) */
