/* Generated By:JJTree: Do not edit this line. NumOrID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class NumOrID extends SimpleNode {
  public NumOrID(int id) {
    super(id);
  }

  public NumOrID(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88e1beade2bd50dda40c9b01d0c59e7f (do not edit this line) */
