/* Generated By:JJTree: Do not edit this line. OpenStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class OpenStatement extends SimpleNode {
  public OpenStatement(int id) {
    super(id);
  }

  public OpenStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=81f97c66e7d3a77931e92c1600a92069 (do not edit this line) */
