/* Generated By:JJTree: Do not edit this line. Option.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Option extends SimpleNode {
  public Option(int id) {
    super(id);
  }

  public Option(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7d924ea84b93cf7306820302369b2e43 (do not edit this line) */
