/* Generated By:JJTree: Do not edit this line. OracleObjectName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class OracleObjectName extends SimpleNode {
  public OracleObjectName(int id) {
    super(id);
  }

  public OracleObjectName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20335ad31812a893848bf4db7e94ce47 (do not edit this line) */
