/* Generated By:JJTree: Do not edit this line. OrderByClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class OrderByClause extends SimpleNode {
  public OrderByClause(int id) {
    super(id);
  }

  public OrderByClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d923f661de2f4b6934d8249a91dfbbce (do not edit this line) */
