/* Generated By:JJTree: Do not edit this line. Parameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Parameter extends SimpleNode {
  public Parameter(int id) {
    super(id);
  }

  public Parameter(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8a276e548924edd90846cb71b4597ad8 (do not edit this line) */
