/* Generated By:JJTree: Do not edit this line. ParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ParameterList extends SimpleNode {
  public ParameterList(int id) {
    super(id);
  }

  public ParameterList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b8c8c3be91d6498a981a9d65ea7e873 (do not edit this line) */
