/* Generated By:JJTree: Do not edit this line. PlSqlInClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlInClause extends SimpleNode {
  public PlSqlInClause(int id) {
    super(id);
  }

  public PlSqlInClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=645358ea0c2bdfd00a8ab8513a079ef4 (do not edit this line) */
