/* Generated By:JJTree: Do not edit this line. PlSqlExponentExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlExponentExpression extends SimpleNode {
  public PlSqlExponentExpression(int id) {
    super(id);
  }

  public PlSqlExponentExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75dbf4d01ac732dface2b7a4f095bcd8 (do not edit this line) */
