/* Generated By:JJTree: Do not edit this line. PlSqlSimpleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlSimpleExpression extends SimpleNode {
  public PlSqlSimpleExpression(int id) {
    super(id);
  }

  public PlSqlSimpleExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b34568f1b5e0486dfd795f6e73a21693 (do not edit this line) */
