/* Generated By:JJTree: Do not edit this line. PlSqlLikeClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlLikeClause extends SimpleNode {
  public PlSqlLikeClause(int id) {
    super(id);
  }

  public PlSqlLikeClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3873286f26d1e0f06f359b066a5e1af (do not edit this line) */
