/* Generated By:JJTree: Do not edit this line. PlSqlUnaryLogicalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlUnaryLogicalExpression extends SimpleNode {
  public PlSqlUnaryLogicalExpression(int id) {
    super(id);
  }

  public PlSqlUnaryLogicalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=998a33c35619f9a7b80f1327b5ef0ad2 (do not edit this line) */
