/* Generated By:JJTree: Do not edit this line. PlSqlExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlExpressionList extends SimpleNode {
  public PlSqlExpressionList(int id) {
    super(id);
  }

  public PlSqlExpressionList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e60d11c49b73932ba0040dd18a2315ad (do not edit this line) */
