/* Generated By:JJTree: Do not edit this line. PlSqlExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlExpression extends SimpleNode {
  public PlSqlExpression(int id) {
    super(id);
  }

  public PlSqlExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e331c92d83f9b1b04ff7e26182a93b36 (do not edit this line) */
