/* Generated By:JJTree: Do not edit this line. PlSqlAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlAndExpression extends SimpleNode {
  public PlSqlAndExpression(int id) {
    super(id);
  }

  public PlSqlAndExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a6d82d6df09a0db5582a82e98e72e9d (do not edit this line) */
