/* Generated By:JJTree: Do not edit this line. PlSqlUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PlSqlUnaryExpression extends SimpleNode {
  public PlSqlUnaryExpression(int id) {
    super(id);
  }

  public PlSqlUnaryExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1d32e6692557a41cf89c09701018831 (do not edit this line) */
