/* Generated By:JJTree: Do not edit this line. PLSQLStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class PLSQLStatement extends SimpleNode {
  public PLSQLStatement(int id) {
    super(id);
  }

  public PLSQLStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=43b132de514cbb6b5c3aeedfced138c8 (do not edit this line) */
