/* Generated By:JavaCC: Do not edit this line. PlSqlTreeConstants.java Version 5.0 */
package newparser;

@SuppressWarnings("all")
public interface PlSqlTreeConstants
{
  public int JJTROOT = 0;
  public int JJTDECLARATIONSECTION = 1;
  public int JJTDECLARATIONS = 2;
  public int JJTIDENTIFIERDECLARATION = 3;
  public int JJTCURSORDECLARATION = 4;
  public int JJTFUNCTIONDECLARATION = 5;
  public int JJTREMFUNC = 6;
  public int JJTTABLETYPEDEF = 7;
  public int JJTCOLUMNDEFINITION = 8;
  public int JJTBINDVARIABLE = 9;
  public int JJTOPTION = 10;
  public int JJTSCALARFUNCBODY = 11;
  public int JJTINLINETVBODY = 12;
  public int JJTMULTITVBODY = 13;
  public int JJTVARIABLEDECLARATION = 14;
  public int JJTCONSTANTDECLARATION = 15;
  public int JJTTYPEDEFINITION = 16;
  public int JJTBASICDATATYPEDEFINITION = 17;
  public int JJTBEGINENDBLOCK = 18;
  public int JJTSEQUENCEOFSTATEMENTS = 19;
  public int JJTPLSQLSTATEMENT = 20;
  public int JJTLABELDECLARATION = 21;
  public int JJTFORALLSTATEMENT = 22;
  public int JJTSQLSTATEMENT = 23;
  public int JJTASSIGNMENTSTATEMENT = 24;
  public int JJTGOTOSTATEMENT = 25;
  public int JJTIFSTATEMENT = 26;
  public int JJTLOOPSTATEMENT = 27;
  public int JJTNORMALLOOP = 28;
  public int JJTWHILELOOP = 29;
  public int JJTFORLOOP = 30;
  public int JJTNUMERICFORLOOPLOOKAHEAD = 31;
  public int JJTNUMERICFORLOOP = 32;
  public int JJTCURSORFORLOOP = 33;
  public int JJTCURSORREFERENCE = 34;
  public int JJTNULLSTATEMENT = 35;
  public int JJTCLOSESTATEMENT = 36;
  public int JJTOPENSTATEMENT = 37;
  public int JJTSAVEPOINTSTATEMENT = 38;
  public int JJTUPDATESTATEMENT = 39;
  public int JJTRETURNINGCLAUSE = 40;
  public int JJTCOLUMNVALUES = 41;
  public int JJTCOLUMNVALUE = 42;
  public int JJTINSERTSTATEMENT = 43;
  public int JJTMERGESTATEMENT = 44;
  public int JJTMERGESETCOLUMN = 45;
  public int JJTDELETESTATEMENT = 46;
  public int JJTQUERYSTATEMENT = 47;
  public int JJTPLSQLEXPRESSION = 48;
  public int JJTPLSQLANDEXPRESSION = 49;
  public int JJTPLSQLUNARYLOGICALEXPRESSION = 50;
  public int JJTPLSQLRELATIONALEXPRESSION = 51;
  public int JJTPLSQLEXPRESSIONLIST = 52;
  public int JJTPLSQLINCLAUSE = 53;
  public int JJTPLSQLBETWEENCLAUSE = 54;
  public int JJTPLSQLLIKECLAUSE = 55;
  public int JJTISNULLCLAUSE = 56;
  public int JJTPLSQLSIMPLEEXPRESSION = 57;
  public int JJTPLSQLMULTIPLICATIVEEXPRESSION = 58;
  public int JJTPLSQLEXPONENTEXPRESSION = 59;
  public int JJTPLSQLUNARYEXPRESSION = 60;
  public int JJTPLSQLPRIMARYEXPRESSION = 61;
  public int JJTTABLECOLUMN = 62;
  public int JJTORACLEOBJECTNAME = 63;
  public int JJTTNSNAME = 64;
  public int JJTRELOP = 65;
  public int JJTTABLENAME = 66;
  public int JJTPARAMETERLIST = 67;
  public int JJTNUMORID = 68;
  public int JJTPARAMETER = 69;
  public int JJTARGUMENTS = 70;
  public int JJTARGUMENT = 71;
  public int JJTSELECTSTATEMENT = 72;
  public int JJTSELECTWITHOUTORDER = 73;
  public int JJTSELECTSET = 74;
  public int JJTSELECT = 75;
  public int JJTSELECTLIST = 76;
  public int JJTSELECTITEM = 77;
  public int JJTSELECTITEMALIAS = 78;
  public int JJTWINDOWINGCLAUSE = 79;
  public int JJTINTOCLAUSE = 80;
  public int JJTDATAITEM = 81;
  public int JJTFROMCLAUSE = 82;
  public int JJTTABLEREFERENCE = 83;
  public int JJTQUERYTABLEEXPRESSION = 84;
  public int JJTTABLECOLLECTIONEXPRESSION = 85;
  public int JJTJOIN = 86;
  public int JJTJOINTYPE = 87;
  public int JJTCOLUMNNAME = 88;
  public int JJTWHERECLAUSE = 89;
  public int JJTGROUPBYCLAUSE = 90;
  public int JJTHAVINGCLAUSE = 91;
  public int JJTORDERBYCLAUSE = 92;
  public int JJTORDERBYEXPRESSION = 93;
  public int JJTFORUPDATECLAUSE = 94;
  public int JJTSQLEXPRESSION = 95;
  public int JJTSQLANDEXPRESSION = 96;
  public int JJTSQLUNARYLOGICALEXPRESSION = 97;
  public int JJTEXISTSCLAUSE = 98;
  public int JJTSQLRELATIONALEXPRESSION = 99;
  public int JJTSQLEXPRESSIONLIST = 100;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 101;
  public int JJTSQLINCLAUSE = 102;
  public int JJTSQLBETWEENCLAUSE = 103;
  public int JJTSQLLIKECLAUSE = 104;
  public int JJTSQLSIMPLEEXPRESSION = 105;
  public int JJTSQLMULTIPLICATIVEEXPRESSION = 106;
  public int JJTSQLEXPONENTEXPRESSION = 107;
  public int JJTSQLUNARYEXPRESSION = 108;
  public int JJTSQLPRIMARYEXPRESSION = 109;
  public int JJTSQLCASEEXPRESSION = 110;
  public int JJTSQLCASTEXPRESSION = 111;
  public int JJTINTERVALEXPRESSION = 112;
  public int JJTFUNCTIONCALL = 113;
  public int JJTFUNCTIONREFERENCE = 114;
  public int JJTFUNCTIONARGUMENTLIST = 115;
  public int JJTFUNCTIONARGUMENT = 116;
  public int JJTTRIMARGUMENTS = 117;
  public int JJTDATETIMEFIELD = 118;
  public int JJTOBJECTREFERENCE = 119;
  public int JJTOUTERJOINEXPRESSION = 120;
  public int JJTSUBQUERY = 121;
  public int JJTID = 122;


  public String[] jjtNodeName = {
    "Root",
    "DeclarationSection",
    "Declarations",
    "IdentifierDeclaration",
    "CursorDeclaration",
    "FunctionDeclaration",
    "RemFunc",
    "TableTypeDef",
    "ColumnDefinition",
    "BindVariable",
    "Option",
    "ScalarFuncBody",
    "InlineTVBody",
    "MultiTVBody",
    "VariableDeclaration",
    "ConstantDeclaration",
    "TypeDefinition",
    "BasicDataTypeDefinition",
    "BeginEndBlock",
    "SequenceOfStatements",
    "PLSQLStatement",
    "LabelDeclaration",
    "ForallStatement",
    "SQLStatement",
    "AssignmentStatement",
    "GotoStatement",
    "IfStatement",
    "LoopStatement",
    "NormalLoop",
    "WhileLoop",
    "ForLoop",
    "NumericForLoopLookahead",
    "NumericForLoop",
    "CursorForLoop",
    "CursorReference",
    "NullStatement",
    "CloseStatement",
    "OpenStatement",
    "SavepointStatement",
    "UpdateStatement",
    "ReturningClause",
    "ColumnValues",
    "ColumnValue",
    "InsertStatement",
    "MergeStatement",
    "MergeSetColumn",
    "DeleteStatement",
    "QueryStatement",
    "PlSqlExpression",
    "PlSqlAndExpression",
    "PlSqlUnaryLogicalExpression",
    "PlSqlRelationalExpression",
    "PlSqlExpressionList",
    "PlSqlInClause",
    "PlSqlBetweenClause",
    "PlSqlLikeClause",
    "IsNullClause",
    "PlSqlSimpleExpression",
    "PlSqlMultiplicativeExpression",
    "PlSqlExponentExpression",
    "PlSqlUnaryExpression",
    "PlSqlPrimaryExpression",
    "TableColumn",
    "OracleObjectName",
    "TNSName",
    "Relop",
    "TableName",
    "ParameterList",
    "NumOrID",
    "Parameter",
    "Arguments",
    "Argument",
    "SelectStatement",
    "SelectWithoutOrder",
    "SelectSet",
    "Select",
    "SelectList",
    "SelectItem",
    "SelectItemAlias",
    "WindowingClause",
    "IntoClause",
    "DataItem",
    "FromClause",
    "TableReference",
    "QueryTableExpression",
    "TableCollectionExpression",
    "Join",
    "JoinType",
    "ColumnName",
    "WhereClause",
    "GroupByClause",
    "HavingClause",
    "OrderByClause",
    "OrderByExpression",
    "ForUpdateClause",
    "SQLExpression",
    "SQLAndExpression",
    "SQLUnaryLogicalExpression",
    "ExistsClause",
    "SQLRelationalExpression",
    "SQLExpressionList",
    "SQLRelationalOperatorExpression",
    "SQLInClause",
    "SQLBetweenClause",
    "SQLLikeClause",
    "SQLSimpleExpression",
    "SQLMultiplicativeExpression",
    "SQLExponentExpression",
    "SQLUnaryExpression",
    "SQLPrimaryExpression",
    "SQLCaseExpression",
    "SQLCastExpression",
    "IntervalExpression",
    "FunctionCall",
    "FunctionReference",
    "FunctionArgumentList",
    "FunctionArgument",
    "TrimArguments",
    "DatetimeField",
    "ObjectReference",
    "OuterJoinExpression",
    "SubQuery",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=55071aa4d32959da71dc43e831ef60aa (do not edit this line) */
