/* Generated By:JJTree: Do not edit this line. QueryTableExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class QueryTableExpression extends SimpleNode {
  public QueryTableExpression(int id) {
    super(id);
  }

  public QueryTableExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=220cba43a95c6eef0e17d31a6cd60757 (do not edit this line) */
