/* Generated By:JJTree: Do not edit this line. QueryStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class QueryStatement extends SimpleNode {
  public QueryStatement(int id) {
    super(id);
  }

  public QueryStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0c9210bb0eebeb26f770ef5007c8577c (do not edit this line) */
