/* Generated By:JJTree: Do not edit this line. Relop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Relop extends SimpleNode {
  public Relop(int id) {
    super(id);
  }

  public Relop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6c70342ef5b75a680103c4ddce62751 (do not edit this line) */
