/* Generated By:JJTree: Do not edit this line. RemFunc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class RemFunc extends SimpleNode {
  public RemFunc(int id) {
    super(id);
  }

  public RemFunc(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=92aad6646b94ae17d8cf0d3efcdfa9f3 (do not edit this line) */
