/* Generated By:JJTree: Do not edit this line. ReturningClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ReturningClause extends SimpleNode {
  public ReturningClause(int id) {
    super(id);
  }

  public ReturningClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ed89355be8a695a7dca8a95872059c2 (do not edit this line) */
