/* Generated By:JJTree: Do not edit this line. Root.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class Root extends SimpleNode {
  public Root(int id) {
    super(id);
  }

  public Root(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fef649f8815fc2945509ed77777f343b (do not edit this line) */
