/* Generated By:JJTree: Do not edit this line. ScalarFuncBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class ScalarFuncBody extends SimpleNode {
  public ScalarFuncBody(int id) {
    super(id);
  }

  public ScalarFuncBody(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9db157d4711ef88e61f656f52c9d468 (do not edit this line) */
