/* Generated By:JJTree: Do not edit this line. SelectItemAlias.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SelectItemAlias extends SimpleNode {
  public SelectItemAlias(int id) {
    super(id);
  }

  public SelectItemAlias(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44d6cd10dca01147220eb9e78885164e (do not edit this line) */
