/* Generated By:JJTree: Do not edit this line. SelectWithoutOrder.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SelectWithoutOrder extends SimpleNode {
  public SelectWithoutOrder(int id) {
    super(id);
  }

  public SelectWithoutOrder(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04592247174d9c4037e8ddfefabfb5b3 (do not edit this line) */
