/* Generated By:JJTree: Do not edit this line. SelectItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SelectItem extends SimpleNode {
  public SelectItem(int id) {
    super(id);
  }

  public SelectItem(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b7b72bfc49836556c3032a88b6fa5281 (do not edit this line) */
