/* Generated By:JJTree: Do not edit this line. SelectStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SelectStatement extends SimpleNode {
  public SelectStatement(int id) {
    super(id);
  }

  public SelectStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e3bd4b187eba559c07b5c9c541d9a53d (do not edit this line) */
