/* Generated By:JJTree: Do not edit this line. SequenceOfStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SequenceOfStatements extends SimpleNode {
  public SequenceOfStatements(int id) {
    super(id);
  }

  public SequenceOfStatements(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae0c2f9f8c12550ebec03d5e9cd88610 (do not edit this line) */
