/* Generated By:JJTree: Do not edit this line. SQLBetweenClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLBetweenClause extends SimpleNode {
  public SQLBetweenClause(int id) {
    super(id);
  }

  public SQLBetweenClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5928b5e28938912ea7cdc71a95ce2e69 (do not edit this line) */
