/* Generated By:JJTree: Do not edit this line. SQLCastExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLCastExpression extends SimpleNode {
  public SQLCastExpression(int id) {
    super(id);
  }

  public SQLCastExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=85ae4cd4d2fe96171c5d44ce6bbcf12d (do not edit this line) */
