/* Generated By:JJTree: Do not edit this line. SQLExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLExpressionList extends SimpleNode {
  public SQLExpressionList(int id) {
    super(id);
  }

  public SQLExpressionList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=48e28227275d30670e491230e3eb21a4 (do not edit this line) */
