/* Generated By:JJTree: Do not edit this line. SQLExponentExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLExponentExpression extends SimpleNode {
  public SQLExponentExpression(int id) {
    super(id);
  }

  public SQLExponentExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c08a3657737b51db3b785573df2548f3 (do not edit this line) */
