/* Generated By:JJTree: Do not edit this line. SQLMultiplicativeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLMultiplicativeExpression extends SimpleNode {
  public SQLMultiplicativeExpression(int id) {
    super(id);
  }

  public SQLMultiplicativeExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1aeeae689029859c78c4735357e9f62c (do not edit this line) */
