/* Generated By:JJTree: Do not edit this line. SQLRelationalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLRelationalExpression extends SimpleNode {
  public SQLRelationalExpression(int id) {
    super(id);
  }

  public SQLRelationalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02f52729d5079e2fb0d8e92e66229157 (do not edit this line) */
