/* Generated By:JJTree: Do not edit this line. SQLStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLStatement extends SimpleNode {
  public SQLStatement(int id) {
    super(id);
  }

  public SQLStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c871706093606c3bff72fbb1887d074a (do not edit this line) */
