/* Generated By:JJTree: Do not edit this line. SQLSimpleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLSimpleExpression extends SimpleNode {
  public SQLSimpleExpression(int id) {
    super(id);
  }

  public SQLSimpleExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b26b90c1aa6e840feceab3713fbba42 (do not edit this line) */
