/* Generated By:JJTree: Do not edit this line. SQLUnaryLogicalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLUnaryLogicalExpression extends SimpleNode {
  public SQLUnaryLogicalExpression(int id) {
    super(id);
  }

  public SQLUnaryLogicalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6bb3a7ff8b65a922c7124b82fb2c152 (do not edit this line) */
