/* Generated By:JJTree: Do not edit this line. SQLUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SQLUnaryExpression extends SimpleNode {
  public SQLUnaryExpression(int id) {
    super(id);
  }

  public SQLUnaryExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8114b13b2691d1136fe9803a1dc9570d (do not edit this line) */
