/* Generated By:JJTree: Do not edit this line. SubQuery.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class SubQuery extends SimpleNode {
  public SubQuery(int id) {
    super(id);
  }

  public SubQuery(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0cfad1a95c692069a25e882b995bf85e (do not edit this line) */
