/* Generated By:JJTree: Do not edit this line. TableCollectionExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class TableCollectionExpression extends SimpleNode {
  public TableCollectionExpression(int id) {
    super(id);
  }

  public TableCollectionExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b7acdf8b65a04aa3d6bed374e7ef1c9 (do not edit this line) */
