/* Generated By:JJTree: Do not edit this line. TableReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class TableReference extends SimpleNode {
  public TableReference(int id) {
    super(id);
  }

  public TableReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e661c987bd2b004d7e5adf1f9377591a (do not edit this line) */
