/* Generated By:JJTree: Do not edit this line. TableColumn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class TableColumn extends SimpleNode {
  public TableColumn(int id) {
    super(id);
  }

  public TableColumn(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=482bc26b3fcedf21bd49667c15947945 (do not edit this line) */
