/* Generated By:JJTree: Do not edit this line. TableTypeDef.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class TableTypeDef extends SimpleNode {
  public TableTypeDef(int id) {
    super(id);
  }

  public TableTypeDef(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4226007fe5ca5047d7c79a8260703b62 (do not edit this line) */
