/* Generated By:JJTree: Do not edit this line. TrimArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class TrimArguments extends SimpleNode {
  public TrimArguments(int id) {
    super(id);
  }

  public TrimArguments(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=507dd6414734a9edb1a61b68fb101260 (do not edit this line) */
