/* Generated By:JJTree: Do not edit this line. UpdateStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class UpdateStatement extends SimpleNode {
  public UpdateStatement(int id) {
    super(id);
  }

  public UpdateStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=746dd4794327a2e09ad42484cbf3bbd0 (do not edit this line) */
