/* Generated By:JJTree: Do not edit this line. VariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class VariableDeclaration extends SimpleNode {
  public VariableDeclaration(int id) {
    super(id);
  }

  public VariableDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed7a54502d28a64594c45edc2757fdf0 (do not edit this line) */
