/* Generated By:JJTree: Do not edit this line. WhereClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class WhereClause extends SimpleNode {
  public WhereClause(int id) {
    super(id);
  }

  public WhereClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=626fae447ab81ef670efc9d905be3b80 (do not edit this line) */
