/* Generated By:JJTree: Do not edit this line. WhileLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class WhileLoop extends SimpleNode {
  public WhileLoop(int id) {
    super(id);
  }

  public WhileLoop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9cd0f1aec6594024ef5afd85286d9cd9 (do not edit this line) */
