/* Generated By:JJTree: Do not edit this line. WindowingClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package newparser;

public
@SuppressWarnings("all")
class WindowingClause extends SimpleNode {
  public WindowingClause(int id) {
    super(id);
  }

  public WindowingClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b456c67ccfe4747ba348fff627d87ac (do not edit this line) */
