/* Generated By:JJTree: Do not edit this line. AlterSession.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class AlterSession extends SimpleNode {
  public AlterSession(int id) {
    super(id);
  }

  public AlterSession(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b1dea5564c8ae039dd9c7464e6a0eeff (do not edit this line) */
