/* Generated By:JJTree: Do not edit this line. AnalyticFunction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class AnalyticFunction extends SimpleNode {
  public AnalyticFunction(int id) {
    super(id);
  }

  public AnalyticFunction(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c62664d4c7e573ae07c1000adfb5efe0 (do not edit this line) */
