/* Generated By:JJTree: Do not edit this line. AnalyticClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class AnalyticClause extends SimpleNode {
  public AnalyticClause(int id) {
    super(id);
  }

  public AnalyticClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6098cd9d2ebbac17b02dce0588a5e7ad (do not edit this line) */
