/* Generated By:JJTree: Do not edit this line. Argument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class Argument extends SimpleNode {
  public Argument(int id) {
    super(id);
  }

  public Argument(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff5daaccf94d3f47825da72e11885ea9 (do not edit this line) */
