/* Generated By:JJTree: Do not edit this line. BeginEndBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class BeginEndBlock extends SimpleNode {
  public BeginEndBlock(int id) {
    super(id);
  }

  public BeginEndBlock(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6428b99ce4b01281f13c7338ee65be9 (do not edit this line) */
