/* Generated By:JJTree: Do not edit this line. BindVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class BindVariable extends SimpleNode {
  public BindVariable(int id) {
    super(id);
  }

  public BindVariable(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56a45e433488a8beadb48d7b4d4fbfe4 (do not edit this line) */
