/* Generated By:JJTree: Do not edit this line. ColumnValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ColumnValue extends SimpleNode {
  public ColumnValue(int id) {
    super(id);
  }

  public ColumnValue(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=157000a05ff466399acfab4889f9c1e3 (do not edit this line) */
