/* Generated By:JJTree: Do not edit this line. ColumnName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ColumnName extends SimpleNode {
  public ColumnName(int id) {
    super(id);
  }

  public ColumnName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1200a1c5bf5b710387633c5cd2aa0fbc (do not edit this line) */
