/* Generated By:JJTree: Do not edit this line. CommitStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class CommitStatement extends SimpleNode {
  public CommitStatement(int id) {
    super(id);
  }

  public CommitStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64b5960e4ae03e7dac9d9ec7382cd9f8 (do not edit this line) */
