/* Generated By:JJTree: Do not edit this line. CompilationUnit.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class CompilationUnit extends SimpleNode {
  public CompilationUnit(int id) {
    super(id);
  }

  public CompilationUnit(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61813a9723b232acfa43eaaa6341f82f (do not edit this line) */
