/* Generated By:JJTree: Do not edit this line. ConnectClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ConnectClause extends SimpleNode {
  public ConnectClause(int id) {
    super(id);
  }

  public ConnectClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c2c0acc851854a1898fddaa8bff3abc (do not edit this line) */
