/* Generated By:JJTree: Do not edit this line. DataItem.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class DataItem extends SimpleNode {
  public DataItem(int id) {
    super(id);
  }

  public DataItem(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=45f6ab6161f7adf0b1e68168ef3cfcda (do not edit this line) */
