/* Generated By:JJTree: Do not edit this line. DatetimeField.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class DatetimeField extends SimpleNode {
  public DatetimeField(int id) {
    super(id);
  }

  public DatetimeField(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7baaa3c9c5a36a50acc34b7cfbe43c56 (do not edit this line) */
