/* Generated By:JJTree: Do not edit this line. DeleteStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class DeleteStatement extends SimpleNode {
  public DeleteStatement(int id) {
    super(id);
  }

  public DeleteStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e06693d0918ec74ab0101aee20a0b0c5 (do not edit this line) */
