/* Generated By:JJTree: Do not edit this line. ExceptionBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ExceptionBlock extends SimpleNode {
  public ExceptionBlock(int id) {
    super(id);
  }

  public ExceptionBlock(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9991af59a42918ffe77f7a4d0052e7f5 (do not edit this line) */
