/* Generated By:JJTree: Do not edit this line. ExceptionHandler.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ExceptionHandler extends SimpleNode {
  public ExceptionHandler(int id) {
    super(id);
  }

  public ExceptionHandler(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22fc894c4a7c0506a86e37046a95cc94 (do not edit this line) */
