/* Generated By:JJTree: Do not edit this line. ExceptionDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ExceptionDeclaration extends SimpleNode {
  public ExceptionDeclaration(int id) {
    super(id);
  }

  public ExceptionDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70bcde2adcea3608e0853745deb01174 (do not edit this line) */
