/* Generated By:JJTree: Do not edit this line. ExistsClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ExistsClause extends SimpleNode {
  public ExistsClause(int id) {
    super(id);
  }

  public ExistsClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e4e6a9a99052fa378ae91acdf53a853 (do not edit this line) */
