/* Generated By:JJTree: Do not edit this line. ExitStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ExitStatement extends SimpleNode {
  public ExitStatement(int id) {
    super(id);
  }

  public ExitStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=120c3f12089f878642f26939c0e3ef45 (do not edit this line) */
