/* Generated By:JJTree: Do not edit this line. FetchStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class FetchStatement extends SimpleNode {
  public FetchStatement(int id) {
    super(id);
  }

  public FetchStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5eaa3fbcce7a751ccc86d608270917cf (do not edit this line) */
