/* Generated By:JJTree: Do not edit this line. ForallStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ForallStatement extends SimpleNode {
  public ForallStatement(int id) {
    super(id);
  }

  public ForallStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f103cc658b0db0d8b4e94d95c4adf1a0 (do not edit this line) */
