/* Generated By:JJTree: Do not edit this line. ForLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ForLoop extends SimpleNode {
  public ForLoop(int id) {
    super(id);
  }

  public ForLoop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4ad412b8efb1450b8190decd38c4fd1d (do not edit this line) */
