/* Generated By:JJTree: Do not edit this line. FunctionCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class FunctionCall extends SimpleNode {
  public FunctionCall(int id) {
    super(id);
  }

  public FunctionCall(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8f27f1694edb5a76e8bf9d97bce660d7 (do not edit this line) */
