/* Generated By:JJTree: Do not edit this line. FunctionBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class FunctionBody extends SimpleNode {
  public FunctionBody(int id) {
    super(id);
  }

  public FunctionBody(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=976527cbb1aaafe52f93df865c8aa111 (do not edit this line) */
