/* Generated By:JJTree: Do not edit this line. GotoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class GotoStatement extends SimpleNode {
  public GotoStatement(int id) {
    super(id);
  }

  public GotoStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0d5d4b6285ec8ddf3c075c9e75c96bb8 (do not edit this line) */
