/* Generated By:JJTree: Do not edit this line. HavingClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class HavingClause extends SimpleNode {
  public HavingClause(int id) {
    super(id);
  }

  public HavingClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=024a800fb79a8077e8f2f080ce1b3115 (do not edit this line) */
