/* Generated By:JJTree: Do not edit this line. ID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ID extends SimpleNode {
  public ID(int id) {
    super(id);
  }

  public ID(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2a6d3a94f0d925502a532cf6fb6f2705 (do not edit this line) */
