/* Generated By:JJTree: Do not edit this line. IdentifierDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class IdentifierDeclaration extends SimpleNode {
  public IdentifierDeclaration(int id) {
    super(id);
  }

  public IdentifierDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ef0faa25af062f34e93d71b91421f3b8 (do not edit this line) */
