/* Generated By:JJTree: Do not edit this line. IsNullClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class IsNullClause extends SimpleNode {
  public IsNullClause(int id) {
    super(id);
  }

  public IsNullClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=02202e8c69a806d1553a1ffe8567d931 (do not edit this line) */
