/* Generated By:JJTree: Do not edit this line. JoinType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class JoinType extends SimpleNode {
  public JoinType(int id) {
    super(id);
  }

  public JoinType(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7aa17808aacea86afd85f40b12f3a30 (do not edit this line) */
