/* Generated By:JJTree: Do not edit this line. Join.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class Join extends SimpleNode {
  public Join(int id) {
    super(id);
  }

  public Join(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=19fcdaa12ea258fab4319035cf71cf4a (do not edit this line) */
