/* Generated By:JJTree: Do not edit this line. LabelDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class LabelDeclaration extends SimpleNode {
  public LabelDeclaration(int id) {
    super(id);
  }

  public LabelDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aba629038882860742f55c98ae08d8ab (do not edit this line) */
