/* Generated By:JJTree: Do not edit this line. LockTableStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class LockTableStatement extends SimpleNode {
  public LockTableStatement(int id) {
    super(id);
  }

  public LockTableStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=99fdd84dbe84dc8f267fd63e0e64e538 (do not edit this line) */
