/* Generated By:JJTree: Do not edit this line. LockMode.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class LockMode extends SimpleNode {
  public LockMode(int id) {
    super(id);
  }

  public LockMode(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55ee11f754bd2de40e2e37be093a6df5 (do not edit this line) */
