/* Generated By:JJTree: Do not edit this line. MergeStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class MergeStatement extends SimpleNode {
  public MergeStatement(int id) {
    super(id);
  }

  public MergeStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10ee6544275570aad16636f923b8b7c7 (do not edit this line) */
