/* Generated By:JJTree: Do not edit this line. MergeSetColumn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class MergeSetColumn extends SimpleNode {
  public MergeSetColumn(int id) {
    super(id);
  }

  public MergeSetColumn(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55aff60cb440c99b5413762dd0212dcf (do not edit this line) */
