/* Generated By:JJTree: Do not edit this line. NormalLoop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class NormalLoop extends SimpleNode {
  public NormalLoop(int id) {
    super(id);
  }

  public NormalLoop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=513d3f30920233c6b34e9ee519d58b69 (do not edit this line) */
