/* Generated By:JJTree: Do not edit this line. NullStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class NullStatement extends SimpleNode {
  public NullStatement(int id) {
    super(id);
  }

  public NullStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1e7fb83d86731cbb63efad88e64ba22a (do not edit this line) */
