/* Generated By:JJTree: Do not edit this line. NumericForLoopLookahead.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class NumericForLoopLookahead extends SimpleNode {
  public NumericForLoopLookahead(int id) {
    super(id);
  }

  public NumericForLoopLookahead(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6a65df0e65e4e2f688f6547d0d87575 (do not edit this line) */
