/* Generated By:JJTree: Do not edit this line. NumOrID.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class NumOrID extends SimpleNode {
  public NumOrID(int id) {
    super(id);
  }

  public NumOrID(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88afe8c4976e0fc8e0f8571530cccb8c (do not edit this line) */
