/* Generated By:JJTree: Do not edit this line. ObjectReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ObjectReference extends SimpleNode {
  public ObjectReference(int id) {
    super(id);
  }

  public ObjectReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fd0478ab017aa6edae8c1dd19ff1a6ca (do not edit this line) */
