/* Generated By:JJTree: Do not edit this line. OpenStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class OpenStatement extends SimpleNode {
  public OpenStatement(int id) {
    super(id);
  }

  public OpenStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eaf53e2d7f63ea9dedd7d6ac6d2d8a4d (do not edit this line) */
