/* Generated By:JJTree: Do not edit this line. OracleObjectName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class OracleObjectName extends SimpleNode {
  public OracleObjectName(int id) {
    super(id);
  }

  public OracleObjectName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5f4e7a5e5654fe1d693b1e2e6b54da0e (do not edit this line) */
