/* Generated By:JJTree: Do not edit this line. OrderByExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class OrderByExpression extends SimpleNode {
  public OrderByExpression(int id) {
    super(id);
  }

  public OrderByExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=88b60b2684e72bc8a9731eb88e1b158c (do not edit this line) */
