/* Generated By:JJTree: Do not edit this line. OrderByClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class OrderByClause extends SimpleNode {
  public OrderByClause(int id) {
    super(id);
  }

  public OrderByClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59c4abc6119c6b91b5768b00c84a7352 (do not edit this line) */
