/* Generated By:JJTree: Do not edit this line. Parameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class Parameter extends SimpleNode {
  public Parameter(int id) {
    super(id);
  }

  public Parameter(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2ce01ff8944cb29c9d6aa2f0132b976a (do not edit this line) */
