/* Generated By:JJTree: Do not edit this line. ParameterList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ParameterList extends SimpleNode {
  public ParameterList(int id) {
    super(id);
  }

  public ParameterList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8279a419286ac829c8cb598bca6c4bca (do not edit this line) */
