/* Generated By:JJTree: Do not edit this line. PlSqlUnaryLogicalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlUnaryLogicalExpression extends SimpleNode {
  public PlSqlUnaryLogicalExpression(int id) {
    super(id);
  }

  public PlSqlUnaryLogicalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=beae8dc70d7bbdf18c98c67e44dac507 (do not edit this line) */
