/* Generated By:JJTree: Do not edit this line. PlSqlBetweenClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlBetweenClause extends SimpleNode {
  public PlSqlBetweenClause(int id) {
    super(id);
  }

  public PlSqlBetweenClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c3946c0f985716ab6300835219cf173 (do not edit this line) */
