/* Generated By:JJTree: Do not edit this line. PlSqlPrimaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlPrimaryExpression extends SimpleNode {
  public PlSqlPrimaryExpression(int id) {
    super(id);
  }

  public PlSqlPrimaryExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4fa4723c77b2117b3bcc254fdbe5f842 (do not edit this line) */
