/* Generated By:JJTree: Do not edit this line. PlSqlAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlAndExpression extends SimpleNode {
  public PlSqlAndExpression(int id) {
    super(id);
  }

  public PlSqlAndExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=944cea2eda8dc853273b1f63e8eb3166 (do not edit this line) */
