/* Generated By:JavaCC: Do not edit this line. PlSqlTreeConstants.java Version 5.0 */
package parser;

@SuppressWarnings("all")
public interface PlSqlTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTVOID = 1;
  public int JJTDECLARATIONSECTION = 2;
  public int JJTDECLARATIONS = 3;
  public int JJTIDENTIFIERDECLARATION = 4;
  public int JJTCURSORDECLARATION = 5;
  public int JJTPRAGMADECLARATION = 6;
  public int JJTPROCEDUREDECLARATION = 7;
  public int JJTPROCEDUREBODY = 8;
  public int JJTUDF = 9;
  public int JJTFUNCTIONBODY = 10;
  public int JJTVARIABLEDECLARATION = 11;
  public int JJTCONSTANTDECLARATION = 12;
  public int JJTTYPEDEFINITION = 13;
  public int JJTBASICDATATYPEDEFINITION = 14;
  public int JJTEXCEPTIONDECLARATION = 15;
  public int JJTBEGINENDBLOCK = 16;
  public int JJTSEQUENCEOFSTATEMENTS = 17;
  public int JJTEXCEPTIONBLOCK = 18;
  public int JJTEXCEPTIONHANDLER = 19;
  public int JJTPLSQLSTATEMENT = 20;
  public int JJTLABELDECLARATION = 21;
  public int JJTFORALLSTATEMENT = 22;
  public int JJTSQLSTATEMENT = 23;
  public int JJTPROCEDURECALL = 24;
  public int JJTPROCEDUREREFERENCE = 25;
  public int JJTASSIGNMENTSTATEMENT = 26;
  public int JJTEXITSTATEMENT = 27;
  public int JJTGOTOSTATEMENT = 28;
  public int JJTIFSTATEMENT = 29;
  public int JJTLOOPSTATEMENT = 30;
  public int JJTNORMALLOOP = 31;
  public int JJTWHILELOOP = 32;
  public int JJTFORLOOP = 33;
  public int JJTNUMERICFORLOOPLOOKAHEAD = 34;
  public int JJTNUMERICFORLOOP = 35;
  public int JJTCURSORFORLOOP = 36;
  public int JJTCURSORREFERENCE = 37;
  public int JJTNULLSTATEMENT = 38;
  public int JJTRAISESTATEMENT = 39;
  public int JJTRETURNSTATEMENT = 40;
  public int JJTCLOSESTATEMENT = 41;
  public int JJTCOMMITSTATEMENT = 42;
  public int JJTFETCHSTATEMENT = 43;
  public int JJTLOCKTABLESTATEMENT = 44;
  public int JJTOPENSTATEMENT = 45;
  public int JJTROLLBACKSTATEMENT = 46;
  public int JJTSETSTATEMENT = 47;
  public int JJTLOCKMODE = 48;
  public int JJTSAVEPOINTSTATEMENT = 49;
  public int JJTUPDATESTATEMENT = 50;
  public int JJTRETURNINGCLAUSE = 51;
  public int JJTCOLUMNVALUES = 52;
  public int JJTCOLUMNVALUE = 53;
  public int JJTINSERTSTATEMENT = 54;
  public int JJTMERGESTATEMENT = 55;
  public int JJTMERGESETCOLUMN = 56;
  public int JJTDELETESTATEMENT = 57;
  public int JJTQUERYSTATEMENT = 58;
  public int JJTPLSQLEXPRESSION = 59;
  public int JJTPLSQLANDEXPRESSION = 60;
  public int JJTPLSQLUNARYLOGICALEXPRESSION = 61;
  public int JJTPLSQLRELATIONALEXPRESSION = 62;
  public int JJTPLSQLEXPRESSIONLIST = 63;
  public int JJTPLSQLINCLAUSE = 64;
  public int JJTPLSQLBETWEENCLAUSE = 65;
  public int JJTPLSQLLIKECLAUSE = 66;
  public int JJTISNULLCLAUSE = 67;
  public int JJTPLSQLSIMPLEEXPRESSION = 68;
  public int JJTPLSQLMULTIPLICATIVEEXPRESSION = 69;
  public int JJTPLSQLEXPONENTEXPRESSION = 70;
  public int JJTPLSQLUNARYEXPRESSION = 71;
  public int JJTPLSQLPRIMARYEXPRESSION = 72;
  public int JJTTABLECOLUMN = 73;
  public int JJTORACLEOBJECTNAME = 74;
  public int JJTTNSNAME = 75;
  public int JJTRELOP = 76;
  public int JJTTABLENAME = 77;
  public int JJTPARAMETERLIST = 78;
  public int JJTNUMORID = 79;
  public int JJTPARAMETER = 80;
  public int JJTARGUMENTS = 81;
  public int JJTARGUMENT = 82;
  public int JJTSELECTSTATEMENT = 83;
  public int JJTSELECTWITHOUTORDER = 84;
  public int JJTSELECTSET = 85;
  public int JJTSELECT = 86;
  public int JJTSELECTLIST = 87;
  public int JJTSELECTITEM = 88;
  public int JJTSELECTITEMALIAS = 89;
  public int JJTANALYTICFUNCTION = 90;
  public int JJTANALYTICCLAUSE = 91;
  public int JJTQUERYPARTITIONCLAUSE = 92;
  public int JJTWINDOWINGCLAUSE = 93;
  public int JJTINTOCLAUSE = 94;
  public int JJTDATAITEM = 95;
  public int JJTFROMCLAUSE = 96;
  public int JJTTABLEREFERENCE = 97;
  public int JJTQUERYTABLEEXPRESSION = 98;
  public int JJTTABLECOLLECTIONEXPRESSION = 99;
  public int JJTJOIN = 100;
  public int JJTJOINTYPE = 101;
  public int JJTCOLUMNNAME = 102;
  public int JJTWHERECLAUSE = 103;
  public int JJTCONNECTCLAUSE = 104;
  public int JJTGROUPBYCLAUSE = 105;
  public int JJTHAVINGCLAUSE = 106;
  public int JJTORDERBYCLAUSE = 107;
  public int JJTORDERBYEXPRESSION = 108;
  public int JJTFORUPDATECLAUSE = 109;
  public int JJTSQLEXPRESSION = 110;
  public int JJTSQLANDEXPRESSION = 111;
  public int JJTSQLUNARYLOGICALEXPRESSION = 112;
  public int JJTEXISTSCLAUSE = 113;
  public int JJTSQLRELATIONALEXPRESSION = 114;
  public int JJTSQLEXPRESSIONLIST = 115;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 116;
  public int JJTSQLINCLAUSE = 117;
  public int JJTSQLBETWEENCLAUSE = 118;
  public int JJTSQLLIKECLAUSE = 119;
  public int JJTSQLSIMPLEEXPRESSION = 120;
  public int JJTSQLMULTIPLICATIVEEXPRESSION = 121;
  public int JJTSQLEXPONENTEXPRESSION = 122;
  public int JJTSQLUNARYEXPRESSION = 123;
  public int JJTSQLPRIMARYEXPRESSION = 124;
  public int JJTSQLCASEEXPRESSION = 125;
  public int JJTSQLCASTEXPRESSION = 126;
  public int JJTINTERVALEXPRESSION = 127;
  public int JJTFUNCTIONCALL = 128;
  public int JJTFUNCTIONREFERENCE = 129;
  public int JJTFUNCTIONARGUMENTLIST = 130;
  public int JJTFUNCTIONARGUMENT = 131;
  public int JJTTRIMARGUMENTS = 132;
  public int JJTDATETIMEFIELD = 133;
  public int JJTOBJECTREFERENCE = 134;
  public int JJTOUTERJOINEXPRESSION = 135;
  public int JJTSUBQUERY = 136;
  public int JJTID = 137;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "void",
    "DeclarationSection",
    "Declarations",
    "IdentifierDeclaration",
    "CursorDeclaration",
    "PragmaDeclaration",
    "ProcedureDeclaration",
    "ProcedureBody",
    "UDF",
    "FunctionBody",
    "VariableDeclaration",
    "ConstantDeclaration",
    "TypeDefinition",
    "BasicDataTypeDefinition",
    "ExceptionDeclaration",
    "BeginEndBlock",
    "SequenceOfStatements",
    "ExceptionBlock",
    "ExceptionHandler",
    "PLSQLStatement",
    "LabelDeclaration",
    "ForallStatement",
    "SQLStatement",
    "ProcedureCall",
    "ProcedureReference",
    "AssignmentStatement",
    "ExitStatement",
    "GotoStatement",
    "IfStatement",
    "LoopStatement",
    "NormalLoop",
    "WhileLoop",
    "ForLoop",
    "NumericForLoopLookahead",
    "NumericForLoop",
    "CursorForLoop",
    "CursorReference",
    "NullStatement",
    "RaiseStatement",
    "ReturnStatement",
    "CloseStatement",
    "CommitStatement",
    "FetchStatement",
    "LockTableStatement",
    "OpenStatement",
    "RollbackStatement",
    "SetStatement",
    "LockMode",
    "SavepointStatement",
    "UpdateStatement",
    "ReturningClause",
    "ColumnValues",
    "ColumnValue",
    "InsertStatement",
    "MergeStatement",
    "MergeSetColumn",
    "DeleteStatement",
    "QueryStatement",
    "PlSqlExpression",
    "PlSqlAndExpression",
    "PlSqlUnaryLogicalExpression",
    "PlSqlRelationalExpression",
    "PlSqlExpressionList",
    "PlSqlInClause",
    "PlSqlBetweenClause",
    "PlSqlLikeClause",
    "IsNullClause",
    "PlSqlSimpleExpression",
    "PlSqlMultiplicativeExpression",
    "PlSqlExponentExpression",
    "PlSqlUnaryExpression",
    "PlSqlPrimaryExpression",
    "TableColumn",
    "OracleObjectName",
    "TNSName",
    "Relop",
    "TableName",
    "ParameterList",
    "NumOrID",
    "Parameter",
    "Arguments",
    "Argument",
    "SelectStatement",
    "SelectWithoutOrder",
    "SelectSet",
    "Select",
    "SelectList",
    "SelectItem",
    "SelectItemAlias",
    "AnalyticFunction",
    "AnalyticClause",
    "QueryPartitionClause",
    "WindowingClause",
    "IntoClause",
    "DataItem",
    "FromClause",
    "TableReference",
    "QueryTableExpression",
    "TableCollectionExpression",
    "Join",
    "JoinType",
    "ColumnName",
    "WhereClause",
    "ConnectClause",
    "GroupByClause",
    "HavingClause",
    "OrderByClause",
    "OrderByExpression",
    "ForUpdateClause",
    "SQLExpression",
    "SQLAndExpression",
    "SQLUnaryLogicalExpression",
    "ExistsClause",
    "SQLRelationalExpression",
    "SQLExpressionList",
    "SQLRelationalOperatorExpression",
    "SQLInClause",
    "SQLBetweenClause",
    "SQLLikeClause",
    "SQLSimpleExpression",
    "SQLMultiplicativeExpression",
    "SQLExponentExpression",
    "SQLUnaryExpression",
    "SQLPrimaryExpression",
    "SQLCaseExpression",
    "SQLCastExpression",
    "IntervalExpression",
    "FunctionCall",
    "FunctionReference",
    "FunctionArgumentList",
    "FunctionArgument",
    "TrimArguments",
    "DatetimeField",
    "ObjectReference",
    "OuterJoinExpression",
    "SubQuery",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=afd8aacffa2537c1e8fcff0b05d61184 (do not edit this line) */
