/* Generated By:JJTree: Do not edit this line. PlSqlLikeClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlLikeClause extends SimpleNode {
  public PlSqlLikeClause(int id) {
    super(id);
  }

  public PlSqlLikeClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a1cc50a04e62e575b918533b272bf6d0 (do not edit this line) */
