/* Generated By:JJTree: Do not edit this line. PlSqlSimpleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlSimpleExpression extends SimpleNode {
  public PlSqlSimpleExpression(int id) {
    super(id);
  }

  public PlSqlSimpleExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=52f2000d966f01c32e05c41c8819145f (do not edit this line) */
