/* Generated By:JJTree: Do not edit this line. PlSqlMultiplicativeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlMultiplicativeExpression extends SimpleNode {
  public PlSqlMultiplicativeExpression(int id) {
    super(id);
  }

  public PlSqlMultiplicativeExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=67920351bbdcbd8b256cd57a9a656d8b (do not edit this line) */
