/* Generated By:JJTree: Do not edit this line. PlSqlRelationalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlRelationalExpression extends SimpleNode {
  public PlSqlRelationalExpression(int id) {
    super(id);
  }

  public PlSqlRelationalExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a32f8846efd9b62095eb2310b40fef6c (do not edit this line) */
