/* Generated By:JJTree: Do not edit this line. PlSqlExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PlSqlExpression extends SimpleNode {
  public PlSqlExpression(int id) {
    super(id);
  }

  public PlSqlExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e8a587cf59ca88006f51d5eab57cda0 (do not edit this line) */
