/* Generated By:JJTree: Do not edit this line. PragmaDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class PragmaDeclaration extends SimpleNode {
  public PragmaDeclaration(int id) {
    super(id);
  }

  public PragmaDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbf34d914e59fcb5d2c207056bf0df54 (do not edit this line) */
