/* Generated By:JJTree: Do not edit this line. ProcedureReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ProcedureReference extends SimpleNode {
  public ProcedureReference(int id) {
    super(id);
  }

  public ProcedureReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ba02b0e19a1ad6353a355106a40edff5 (do not edit this line) */
