/* Generated By:JJTree: Do not edit this line. ProcedureDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ProcedureDeclaration extends SimpleNode {
  public ProcedureDeclaration(int id) {
    super(id);
  }

  public ProcedureDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=55d2815db44c0fac5244f0cda6e2099d (do not edit this line) */
