/* Generated By:JJTree: Do not edit this line. ProcedureCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ProcedureCall extends SimpleNode {
  public ProcedureCall(int id) {
    super(id);
  }

  public ProcedureCall(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1ec94c199103062f7fdbf3b0bbc5f811 (do not edit this line) */
