/* Generated By:JJTree: Do not edit this line. ProcedureBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ProcedureBody extends SimpleNode {
  public ProcedureBody(int id) {
    super(id);
  }

  public ProcedureBody(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b0ebd8cd4908f12eaad3b606ac8ea13e (do not edit this line) */
