/* Generated By:JJTree: Do not edit this line. QueryPartitionClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class QueryPartitionClause extends SimpleNode {
  public QueryPartitionClause(int id) {
    super(id);
  }

  public QueryPartitionClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d229414fd69d51a61a71c05ebb7523d8 (do not edit this line) */
