/* Generated By:JJTree: Do not edit this line. RaiseStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class RaiseStatement extends SimpleNode {
  public RaiseStatement(int id) {
    super(id);
  }

  public RaiseStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=62f9ff0a5135206e9c3d9fc989515390 (do not edit this line) */
