/* Generated By:JJTree: Do not edit this line. Relop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class Relop extends SimpleNode {
  public Relop(int id) {
    super(id);
  }

  public Relop(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5131be0982122190ce68540d51277c2f (do not edit this line) */
