/* Generated By:JJTree: Do not edit this line. ReturnStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class ReturnStatement extends SimpleNode {
  public ReturnStatement(int id) {
    super(id);
  }

  public ReturnStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=960dfc2b4a9a76d3331295c62db83af2 (do not edit this line) */
