/* Generated By:JJTree: Do not edit this line. RollbackStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class RollbackStatement extends SimpleNode {
  public RollbackStatement(int id) {
    super(id);
  }

  public RollbackStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3edb44542fc808489fc24b53dd9f8f7 (do not edit this line) */
