/* Generated By:JJTree: Do not edit this line. SavepointStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SavepointStatement extends SimpleNode {
  public SavepointStatement(int id) {
    super(id);
  }

  public SavepointStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a153f5ac51b804871cebdff130609426 (do not edit this line) */
