/* Generated By:JJTree: Do not edit this line. SelectSet.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SelectSet extends SimpleNode {
  public SelectSet(int id) {
    super(id);
  }

  public SelectSet(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3758f3d039d6bfe6397c78cde2a4d875 (do not edit this line) */
