/* Generated By:JJTree: Do not edit this line. SelectWithoutOrder.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SelectWithoutOrder extends SimpleNode {
  public SelectWithoutOrder(int id) {
    super(id);
  }

  public SelectWithoutOrder(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf72f3ece8adc89869ba3a8145f7fdaf (do not edit this line) */
