/* Generated By:JJTree: Do not edit this line. SelectList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SelectList extends SimpleNode {
  public SelectList(int id) {
    super(id);
  }

  public SelectList(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d8aaeca8f332014e235076f4d627018 (do not edit this line) */
