/* Generated By:JJTree: Do not edit this line. Select.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class Select extends SimpleNode {
  public Select(int id) {
    super(id);
  }

  public Select(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7b93487f0cb6060dacbfb03ac4ab49d (do not edit this line) */
