/* Generated By:JJTree: Do not edit this line. SelectStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SelectStatement extends SimpleNode {
  public SelectStatement(int id) {
    super(id);
  }

  public SelectStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9f3e28fd4483e2094e13e1021c4cf354 (do not edit this line) */
