/* Generated By:JJTree: Do not edit this line. SequenceOfStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SequenceOfStatements extends SimpleNode {
  public SequenceOfStatements(int id) {
    super(id);
  }

  public SequenceOfStatements(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=745f68ef0b757952b1b472991846bcaf (do not edit this line) */
