/* Generated By:JJTree: Do not edit this line. SetStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SetStatement extends SimpleNode {
  public SetStatement(int id) {
    super(id);
  }

  public SetStatement(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04cd45155f3284a0895dfecbde9e8db5 (do not edit this line) */
