/* Generated By:JJTree: Do not edit this line. SQLAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLAndExpression extends SimpleNode {
  public SQLAndExpression(int id) {
    super(id);
  }

  public SQLAndExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9e442357cb5875ce25539e69130e81a (do not edit this line) */
