/* Generated By:JJTree: Do not edit this line. SQLBetweenClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLBetweenClause extends SimpleNode {
  public SQLBetweenClause(int id) {
    super(id);
  }

  public SQLBetweenClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2391e7510f4034dd89189a790bdf454d (do not edit this line) */
