/* Generated By:JJTree: Do not edit this line. SQLCastExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLCastExpression extends SimpleNode {
  public SQLCastExpression(int id) {
    super(id);
  }

  public SQLCastExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa356cd54efc9a62b9677c95cbad74d3 (do not edit this line) */
