/* Generated By:JJTree: Do not edit this line. SQLCaseExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLCaseExpression extends SimpleNode {
  public SQLCaseExpression(int id) {
    super(id);
  }

  public SQLCaseExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ab05a9ae8c1ccecbcda3c75247d13fd3 (do not edit this line) */
