/* Generated By:JJTree: Do not edit this line. SQLInClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLInClause extends SimpleNode {
  public SQLInClause(int id) {
    super(id);
  }

  public SQLInClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86867621dc6640b8f2a673cc51906840 (do not edit this line) */
