/* Generated By:JJTree: Do not edit this line. SQLLikeClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLLikeClause extends SimpleNode {
  public SQLLikeClause(int id) {
    super(id);
  }

  public SQLLikeClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e433295323b8ebd1cea6a01ed6d8258 (do not edit this line) */
