/* Generated By:JJTree: Do not edit this line. SQLMultiplicativeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLMultiplicativeExpression extends SimpleNode {
  public SQLMultiplicativeExpression(int id) {
    super(id);
  }

  public SQLMultiplicativeExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=51b93f3ab3e2a3e3634d0eb60d348ee6 (do not edit this line) */
