/* Generated By:JJTree: Do not edit this line. SQLPrimaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLPrimaryExpression extends SimpleNode {
  public SQLPrimaryExpression(int id) {
    super(id);
  }

  public SQLPrimaryExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=77355b4adf605aa1d33fcfbf082c7d17 (do not edit this line) */
