/* Generated By:JJTree: Do not edit this line. SQLUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class SQLUnaryExpression extends SimpleNode {
  public SQLUnaryExpression(int id) {
    super(id);
  }

  public SQLUnaryExpression(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9376bba8f4cf1e9ac94b492d23fbf6da (do not edit this line) */
