/* Generated By:JJTree: Do not edit this line. TableReference.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class TableReference extends SimpleNode {
  public TableReference(int id) {
    super(id);
  }

  public TableReference(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=101e2c3758d45e7489231d89fddd0fc4 (do not edit this line) */
