/* Generated By:JJTree: Do not edit this line. TableName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class TableName extends SimpleNode {
  public TableName(int id) {
    super(id);
  }

  public TableName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3bc368c30c26f4bbd5764e5b8d90058f (do not edit this line) */
