/* Generated By:JJTree: Do not edit this line. TNSName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class TNSName extends SimpleNode {
  public TNSName(int id) {
    super(id);
  }

  public TNSName(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3242561421f383997df0f9740f7b695f (do not edit this line) */
