/* Generated By:JJTree: Do not edit this line. TrimArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class TrimArguments extends SimpleNode {
  public TrimArguments(int id) {
    super(id);
  }

  public TrimArguments(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf6b8ac9dc47477af4ca3e7a23f030b3 (do not edit this line) */
