/* Generated By:JJTree: Do not edit this line. TypeDefinition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class TypeDefinition extends SimpleNode {
  public TypeDefinition(int id) {
    super(id);
  }

  public TypeDefinition(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6662b836473078bdd34d9f025ebf529b (do not edit this line) */
