/* Generated By:JJTree: Do not edit this line. UDF.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class UDF extends SimpleNode {
  public String funcName;
	public UDF(int id) {
    super(id);
  }

  public UDF(PlSql p, int id) {
    super(p, id);
  }
  
}
/* JavaCC - OriginalChecksum=7a66e9e346b4eefd3aff0a383e9ab287 (do not edit this line) */
