/* Generated By:JJTree: Do not edit this line. VariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class VariableDeclaration extends SimpleNode {
  public VariableDeclaration(int id) {
    super(id);
  }

  public VariableDeclaration(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce199daa77ddcf3db4f2594ad5c2515e (do not edit this line) */
