/* Generated By:JJTree: Do not edit this line. WhereClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class WhereClause extends SimpleNode {
  public WhereClause(int id) {
    super(id);
  }

  public WhereClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c5101da160fb3993b45dfeb36cd6c01 (do not edit this line) */
