/* Generated By:JJTree: Do not edit this line. WindowingClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
@SuppressWarnings("all")
class WindowingClause extends SimpleNode {
  public WindowingClause(int id) {
    super(id);
  }

  public WindowingClause(PlSql p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=989c046c1c135f25adaacc4570a1c37b (do not edit this line) */
